### ISSUE TITLE
Mini 11S / 4.0.7 - Can't install hack

### ISSUE THREAD

**Issue by andrewjbates** [guino/Merkury1080P#31]
# Background

I recently applied the hack to a Mini 11S and two Mini 7Cs I bought a few months ago. Based on the success of those, I picked up another Mini 11S. This new one won't hack and it's not clear why.

A few notes:
* I've attempted this with 4 different SD cards, including the SD card I used to hack the first Mini 11S
* I have no trouble getting port 8090 open and doing `/proc/cmdline` and `/devices/deviceinfo`
* The firmware version (4.0.7) is the same as the working camera
* I confirmed the reset button *does* work
* I saw https://github.com/guino/Merkury1080P/issues/28 which doesn't help because those issues began after a successful hack
* I saw https://github.com/guino/Merkury1080P/issues/29 which led me to https://github.com/guino/BazzDoorbell/issues/13 , which didn't solve this. 
    * I confirmed the env file has the correct format in **HxD**
    * I tried `env` two different ways:
        * `bootargs=mem=64M ` ...
        * `setenv bootargs mem=64M ` ...
    * I also tried `ppsMmcTool.txt` two different ways:
        * ... `env import 81C08000` ... (from ppshack2)
        * ... `env import 42000000` ... (from this repo)

## Outputs
I'm posting the both twice, once in `code blocks` (to clarify formatting) and *quotes* (to be readable and not so wide)

### /proc/cmdline
```
setenv bootargs mem=64M console=ttySAK0,115200n8 loglevel=10   mtdparts=spi0.0:256k(bld),64k(env),64k(enc),64k(sysflg),3m(sys),4032k(app),640k(cfg) ppsAppParts=5 ip=192.168.1.99:::255.255.255.0 eth=00:55:7b:b5:7d:f7 usb_other
```
>setenv bootargs mem=64M console=ttySAK0,115200n8 loglevel=10   mtdparts=spi0.0:256k(bld),64k(env),64k(enc),64k(sysflg),3m(sys),4032k(app),640k(cfg) ppsAppParts=5 ip=192.168.1.99:::255.255.255.0 eth=00:55:7b:b5:7d:f7 usb_other

### /devices/deviceinfo
```json
{"devname":"Smart Home Camera","model":"Mini 11S","serialno":"101934489","softwareversion":"4.0.7","hardwareversion":"M11S_A2_V20_GC1","firmwareversion":"ppstrong-a3-tuya2_merkury-4.0.7.20210624","identity":"M6H0096K6V00901104","authkey":"APvLAil8K5zXxiRDkFmY21awjKzDCcCt","deviceid":"pp0102312aa2284cc972","pid":"aaa","WiFi MAC":"84:7a:b6:55:1d:57","ETH MAC":"00:00:00:00:00:00"}
```
>{"devname":"Smart Home Camera","model":"Mini 11S","serialno":"101934489","softwareversion":"4.0.7","hardwareversion":"M11S_A2_V20_GC1","firmwareversion":"ppstrong-a3-tuya2_merkury-4.0.7.20210624","identity":"M6H0096K6V00901104","authkey":"APvLAil8K5zXxiRDkFmY21awjKzDCcCt","deviceid":"pp0102312aa2284cc972","pid":"aaa","WiFi MAC":"84:7a:b6:55:1d:57","ETH MAC":"00:00:00:00:00:00"}

## Final Notes
* Implicit with the hack not working, but making it explicit: I can't get telnetd running to do any further onboard investigation
* Please let me know anything else you need to see / want me to try
* Edited to add more detail around the work I did with ppshack2

**Comment by guino** [comment]
@andrewjbates can you post a zip of your env, initrun.sh and ppsMmcTool.txt -- the files you need to install the hack are exactly these: https://github.com/guino/Merkury1080P/tree/main/mmc (so the env file should start with **hack=** which wasn't listed in your post). If you get to install the hack with just the 3 files in the SD card you'll know it worked because it will create a home directory in the SD card, then you can add other files for telnet, etc.

**Comment by andrewjbates** [comment]
@guino Based on your note that the env file was wrong, I decided to start over from scratch— re-downloading, restaging everything. I’m not sure what I did wrong the first time, but it all worked this time. Thanks for your help!
