### ISSUE TITLE
Rtsp stream does not start without the internet

### ISSUE THREAD

**Issue by RomchikL** [guino/Merkury1080P#35]
Hello!

I rooted my camera (Laxihub M3-TY(Mini 7s)) and rtsp stream works perfectly. Thanks a lot, but I have one question.
When I turn on the camera with internet, the stream works, but
when I turn on the camera without internet, the stream doesn't work.

Can it be fixed with root?
```
{"devname":"Smart Home Camera","model":"Mini 7S","serialno":"100372114","softwareversion":"4.0.6","hardwareversion":"M7S_A2_V10_F37","firmwareversion":"ppstrong-a3-tuya2_laxi-4.0.6.20210326","identity":"XXX","authkey":"XXX","deviceid":"XXX","pid":"aaa","WiFi MAC":"b4:fb:e3:bb:1f:7e","ETH MAC":"00:00:00:00:00:00"}
```

**Comment by guino** [comment]
@RomchikL this is a known limitation -- the tuya application in the camera only fully starts after it connects to the tuya servers (using internet) so it can set the date+time on the device. 

To work with the device offilne these are the options:
https://github.com/guino/BazzDoorbell/wiki/%5BHow-to%5D-Use-the-device-OFFLINE-(disconnected-from-tuya-servers)-%3F
