### ISSUE TITLE
tuya_config.json missing in LSC Smart Home Camera Mini 16S

### ISSUE THREAD

**Issue by jstam84** [guino/Merkury1080P#43]
Got the same camera as [this one](https://github.com/guino/Merkury1080P/issues/6). It looks as though the tuya_config.json file is missing from the app.tar.gz that's untarred from /dev/mtdblock5. I checked this via telnet btw..  Patched ppsapp is running on the camera, but no ONVIF/RTSP. 

Two questions;
1) Is this expected behaviour in this (and/or other) rebranded cameras? 
2) can someone give me a default tuya_config.json so I can test the rest?

If true, then initrun.sh should be patched to copy a default config file?

Thanks in advance!

**Comment by jstam84** [comment]
Okay, stating the obvious here. You have to setup the camera with the LSC app first! This is missing from the docs imho ;)

Issue can be closed

**Comment by guino** [comment]
@jstam84 glad you figured it out -- I was traveling the past week, sorry for the delayed reply, but that was going to be my first question: you always have to enroll the device in the app so it initializes the devices/settings/etc.
