### ISSUE TITLE
GNC-CW020, Firmware V4.40.5

### ISSUE THREAD

**Issue by ja-p** [guino/Merkury1080P#47]
Hello,

I have been reading the guides and I can't seem to get past the first few steps. 

I have a GNC-CW020 camera which the Geeni app says it has the firmware V4.40.5. I tried formatting (multiple ways) 2 SD Cards a bunch of times and copying the files, but I could never get them to have any sort of effect (Not even the ppsFactoryTool.txt). Ports always are the same (80,8090,23 closed and 6668 open). The device seems to boot as usual and if it had Wifi already set up, connects to it and starts recording in the DCIM folder (which contains .info and .media files)

Looks like this is a bad sign on the compatibility of this device, although from what I read this should be a 4.X firmware and it should somewhat work.

Do you have any insight on what could be wrong or if this particular device/firmware is even compatible?

Thank you for the work on these repos!

**Comment by guino** [comment]
@ja-p I have never heard of a 4.**40**.x firmware until now -- all the ones we had seen were 4.**0**.x. This is most likely the reason why nothing is working. Without the device or someone with the device to open it and try things on the serial port (or extract the firmware) there's not much we can do.

**Comment by ja-p** [comment]
@guino That's unfortunate. I don't have the tools or skills for that, so I cannot assist with this for now.  Hopefully this changes in the future. Thanks for the reply!
