### ISSUE TITLE
I can't even get the WebUI with the SD Card In

### ISSUE THREAD

**Issue by MapGuy11** [guino/Merkury1080P#58]
Hello and great project you have here.
I was working through the steps with a cheap Micro Center "AQIA 1080p Indoor Camera" TuYa just wanted to mess with it and maybe get some kind of RTSP/ONVIF. Instead of the garbage TuYa cloud. Here is the camera on MC and TuYa if it helps at all. Attached are also the files I put into the SD card as I may have misinterpreted the instructions. But I can't for the life of me get to any kind of WebUI/Telnet nothing. Any assistance is greatly appreciated. 

MC: https://www.microcenter.com/product/665651/aqia-sc009-wl2-hd-security-camera
TuYa: https://expo.tuya.com/product/1106283
FCC: https://fcc.report/FCC-ID/2A789SC009
GDrive with all the files on SDcard: https://drive.google.com/drive/folders/1iwwD8jkjLkZo0bQ1Z1t6W4BXGzEPvjMU?usp=sharing

**Comment by MapGuy11** [comment]
@guino Any ideas?

**Comment by guino** [comment]
Sorry, I have not seen this device before so someone would have to open it and dump the firmware or try UART access before I could tell you anything about it.

Please notice Tuya is only a platform/service, they work with any manufacturer to put their devices into a working phone app. There are hundreds (likely thousands) of manufacturers using tuya so chances are high that the instructions we have will not work for most tuya devices out there, that is, unless they were made by the same manufacturer (even if rebranded as something else).

**Comment by MapGuy11** [comment]
> Sorry, I have not seen this device before so someone would have to open it and dump the firmware or try UART access before I could tell you anything about it.
> 
> Please notice Tuya is only a platform/service, they work with any manufacturer to put their devices into a working phone app. There are hundreds (likely thousands) of manufacturers using tuya so chances are high that the instructions we have will not work for most tuya devices out there, that is, unless they were made by the same manufacturer (even if rebranded as something else).

Thank you for the info!
