### ISSUE TITLE
change in ppsapp after reinstall

### ISSUE THREAD

**Issue by gielie** [guino/Merkury1080P#8]
after my system crashed and my sd card got wiped I tried to do the hack all over again without any luck.
The problem I notices is my ppsapp MD5 checksum changed, does this mean I have a different ppsapp file?

device info
`{"devname":"Smart Home Camera",
"model":"Mini16S",
"serialno":"100142661",
"softwareversion":"4.0.6",
"hardwareversion":"M16S_A2_V10_F37",
"firmwareversion":"ppstrong-a3-tuya2_lsc-4.0.6.20210311",
"identity":"M1K006CF3B02016906",
"authkey":"diBYYPK2YHTXS4xEp46u3CVh9UJqtbds",
"deviceid":"pp01663ec68134948693",
"pid":"aaa",
"WiFi MAC":"b4:fb:e3:a5:74:ec",
"ETH MAC":"00:00:00:00:00:00"}`

cmdline info
`mem=64M console=ttySAK0,115200n8 loglevel=10 mtdparts=spi0.0:256k(bld),64k(env),64k(enc),64k(sysflg),3m(sys),4032k(app),640k(cfg) ppsAppParts=5 ip=0 - ip=30;/mnt/mmc01/initrun.sh)&:::::;date>/tmp/hack;(sleep`

and attached the new ppsapp file.

[ppsapp.zip](https://github.com/guino/Merkury1080P/files/7205258/ppsapp.zip)
can anyone help me with this one?

**Comment by guino** [comment]
Let me know if you closed this by accident and you still need help (by re-opening the issue)

**Comment by gielie** [comment]
im a Mac user and for some reason I get different results between Mac and pc, I can't handle a pc. but I closed this on purpose, I need to figure it out bij myself. thanks for the concern.

**Comment by williamkennyAK** [comment]
@gielie check out https://github.com/guino/Merkury1080P/issues/9
I found that I was able to do the hack and just enable onvif in the tuya_config.json file without patching ppsapp in 4.0.6.
